### ISSUE TITLE
How about support Cocoapods?

### ISSUE THREAD

**Issue by ipeisong** [ShareSDKPlatform/ShareSDK-for-iOS#5]
Would be great to support Cocoapods, thanks.

**Comment by favoyang** [comment]
+1 for cocoapods

**Comment by gastrodia** [comment]
+1 for cocoapods

**Comment by skyz319** [comment]
+1 for cocoapods

**Comment by kainecy** [comment]
+1 for cocoapods

**Comment by xibo55** [comment]
+1 for cocoapods

**Comment by buhe** [comment]
+1 for cocoapods

**Comment by callmewhy** [comment]
+1 for cocoapods!

**Comment by wyd2004** [comment]
+1 for cocoapods!

**Comment by shingwasix** [comment]
Unofficial support : )
https://github.com/shingwasix/MobShareSDK

**Comment by isaced** [comment]
+1 for cocoapods!

**Comment by JinghuangLiu** [comment]
We have already supported Cocoapods.Please Visit the webpage http://wiki.mob.com/cocoapods集成sharesdk标准版/
