### ISSUE TITLE
QQ分享成功不回调问题，求解决。

### ISSUE THREAD

**Issue by zjutwhw** [ShareSDKPlatform/ShareSDK-for-iOS#7]
- (BOOL)handleOpenURL:(NSURL *)url
{
        [QQApiInterface handleOpenURL:url delegate:self]
        .....
} 

//但onResp不回调
- (void)onResp:(QQBaseResp *)resp
{
}

有没有人遇到相同的问题。

**Comment by wangyansnow** [comment]
我遇到了这个问题,能说一下最后是怎么解决的吗?

**Comment by JinghuangLiu** [comment]
官网联系下我们技术支持

发自我的 iPad
